language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - php composer.phar install
  - chmod 777 travis.phpunit.xml

script:
  - cd $TRAVIS_BUILD_DIR;
  - mkdir -p build/logs
  - vendor/phpunit/phpunit/composer/bin/phpunit -c $TRAVIS_BUILD_DIR/travis.phpunit.xml
  - php vendor/bin/coveralls -v
