<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'InstallScripts\Script'                                 => __DIR__ . '/Script.php',
  'InstallScripts\Controller\SetController'               => __DIR__ . '/Controller/SetController.php',
  'InstallScripts\Controller\ListController'              => __DIR__ . '/Controller/ListController.php',
  'InstallScripts\Controller\AbstractActionController'    => __DIR__ . '/Controller/AbstractActionController.php',
  'InstallScripts\Controller\VersionsController'          => __DIR__ . '/Controller/VersionsController.php',
  'InstallScripts\Controller\UpdateController'            => __DIR__ . '/Controller/UpdateController.php',
  'InstallScripts\Controller\InstallController'           => __DIR__ . '/Controller/InstallController.php',
  'InstallScripts\Controller\ConfigController'            => __DIR__ . '/Controller/ConfigController.php',
  'InstallScripts\Controller\SetLatestController'         => __DIR__ . '/Controller/SetLatestController.php',
  'InstallScripts\Locator'                                => __DIR__ . '/Locator.php',
  'InstallScripts\ScriptInterface'                        => __DIR__ . '/ScriptInterface.php',
  'InstallScripts\Exception\ActionControllerException'    => __DIR__ . '/Exception/ActionControllerException.php',
  'InstallScripts\Exception\LocatorException'             => __DIR__ . '/Exception/LocatorException.php',
  'InstallScripts\Exception\ExceptionInterface'           => __DIR__ . '/Exception/ExceptionInterface.php',
  'InstallScripts\Exception\StorageAdapterException'      => __DIR__ . '/Exception/StorageAdapterException.php',
  'InstallScripts\Exception\ScriptException'              => __DIR__ . '/Exception/ScriptException.php',
  'InstallScripts\Storage'                                => __DIR__ . '/Storage.php',
  'InstallScripts\StorageAdapter\StorageAdapterInterface' => __DIR__ . '/StorageAdapter/StorageAdapterInterface.php',
  'InstallScripts\StorageAdapter\FileStorageAdapter'      => __DIR__ . '/StorageAdapter/FileStorageAdapter.php',
);
